"use client";

import { useState, type FormEvent } from "react";
import NextImage from "next/image";
import { Archive, AudioLines, ChevronRight, Download, Ellipsis, File, FileImage, FileText, Film, FolderPlus, Grid2X2, Image as ImageIcon, Info, List, Move, Pencil, Play, Search, Trash2, Upload, X } from "lucide-react";
import type { FilesView } from "@/lib/files-view";
import { assignFolderTree, deleteLibraryEntities, descendantFolderIds, kindFor, newId, updateLibrary, useAssetLibrary, type LibraryFile, type LibraryFolder, type LibraryKind } from "@/lib/asset-library";

type Props = { view?: FilesView; projectId?: string | null; projectName?: string; clientId?: string | null; compact?: boolean };
export function AssetLibrary({ view, projectId = null, projectName, clientId = null, compact = false }: Props) {
  const stored = useAssetLibrary(); const [folderId, setFolderId] = useState<string | null>(null); const [query, setQuery] = useState(""); const [searchEverywhere, setSearchEverywhere] = useState(false); const [dialog, setDialog] = useState<"folder" | "upload" | null>(null); const [preview, setPreview] = useState<LibraryFile | null>(null); const [details, setDetails] = useState<LibraryFile | LibraryFolder | null>(null); const [selected, setSelected] = useState<Set<string>>(new Set()); const [clientFilter, setClientFilter] = useState(""); const [projectFilter, setProjectFilter] = useState(""); const [kindFilter, setKindFilter] = useState<LibraryKind | "">(""); const [sort, setSort] = useState<"newest" | "name" | "size">("newest"); const [dense, setDense] = useState(false);
  const serverFolders: LibraryFolder[] = (view?.groups ?? []).flatMap((group) => group.folders.map((folder) => ({ id: folder.id, name: folder.name, clientId: group.clientId, projectId: group.projectId, parentFolderId: folder.parent_folder_id, createdAt: folder.created_at, createdBy: "Workspace member" })));
  const serverFiles: LibraryFile[] = (view?.groups ?? []).flatMap((group) => group.files.map((item) => ({ id: item.id, name: item.file.name, kind: mimeKind(item.file.mime_type, item.file.name), mimeType: item.file.mime_type, size: item.file.size_bytes, url: view?.workspaceId && item.file.status === "READY" ? `/api/workspaces/${view.workspaceId}/projects/${group.projectId}/files/${item.id}/download/` : null, preview: null, uploadedBy: "Workspace member", uploadedAt: item.created_at, folderId: item.folder_id, clientId: group.clientId, projectId: group.projectId })));
  const folders = merge(serverFolders, stored.folders).filter((item) => !stored.deletedIds.includes(item.id) && (!projectId || item.projectId === projectId));
  const files = merge(serverFiles, stored.files).filter((item) => !stored.deletedIds.includes(item.id) && (!projectId || item.projectId === projectId));
  const current = folders.find((item) => item.id === folderId) ?? null; const recursiveSearch = searchEverywhere && Boolean(query.trim()); const filteredProjects = (view?.groups ?? []).filter((group) => !clientFilter || group.clientId === clientFilter); const scopeFolders = sortFolders(folders.filter((item) => (recursiveSearch || item.parentFolderId === folderId) && matches(item.name, query) && matchesRelation(item, clientFilter, projectFilter)), sort); const scopeFiles = sortFiles(files.filter((item) => (recursiveSearch || item.folderId === folderId) && matches(item.name, query) && matchesRelation(item, clientFilter, projectFilter) && (!kindFilter || item.kind === kindFilter)), sort);
  const crumbs = folderTrail(current, folders);
  const toggleSelected = (id: string) => setSelected((value) => { const next = new Set(value); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const deleteSelected = () => { if (!selected.size || !confirm(`Delete ${selected.size} selected item${selected.size === 1 ? "" : "s"}?`)) return; updateLibrary((state) => deleteLibraryEntities(state, selected)); setSelected(new Set()); };
  return <div className={compact ? "asset-library compact" : "asset-library"}>
    <div className="al-head"><div>{!compact && <><p className="eyebrow">Central asset library</p><h1>Files</h1><p>Creative files, folders, clients, and projects—connected in one place.</p></>}</div><div><button onClick={() => setDialog("folder")}><FolderPlus />New folder</button><button className="primary" onClick={() => setDialog("upload")}><Upload />Upload</button></div></div>
    <div className="al-toolbar"><nav><button onClick={() => setFolderId(null)}>{projectName || "All Files"}</button>{crumbs.map((folder) => <span key={folder.id}><ChevronRight /><button onClick={() => setFolderId(folder.id)}>{folder.name}</button></span>)}</nav><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search this location…" /></label></div>
    <div className="al-controls">
      <label className="al-scope"><input type="checkbox" checked={searchEverywhere} onChange={(event) => setSearchEverywhere(event.target.checked)} />Search all folders</label>
      {!projectId && <><select aria-label="Filter by client" value={clientFilter} onChange={(event) => { setClientFilter(event.target.value); setProjectFilter(""); }}><option value="">All clients</option>{view?.clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select><select aria-label="Filter by project" value={projectFilter} onChange={(event) => setProjectFilter(event.target.value)}><option value="">All projects</option>{filteredProjects.map((group) => <option key={group.projectId} value={group.projectId}>{group.projectName}</option>)}</select></>}
      <select aria-label="Filter by file type" value={kindFilter} onChange={(event) => setKindFilter(event.target.value as LibraryKind | "")}><option value="">All file types</option><option value="video">Video</option><option value="audio">Audio</option><option value="image">Images</option><option value="document">Documents</option><option value="source">Source files</option><option value="other">Other</option></select>
      <select aria-label="Sort assets" value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="newest">Newest first</option><option value="name">Name A–Z</option><option value="size">Largest first</option></select>
      <div className="al-view-toggle"><button className={!dense ? "active" : ""} onClick={() => setDense(false)} aria-label="Card view" aria-pressed={!dense}><Grid2X2 /></button><button className={dense ? "active" : ""} onClick={() => setDense(true)} aria-label="List view" aria-pressed={dense}><List /></button></div>
    </div>
    {selected.size > 0 && <div className="al-bulk"><strong>{selected.size} selected</strong><button onClick={() => setSelected(new Set())}>Clear</button><button className="danger" onClick={deleteSelected}><Trash2 />Delete</button></div>}
    {recursiveSearch && <p className="al-results-note">Showing matches from every folder in {projectName || "Files"}.</p>}
    {scopeFolders.length > 0 && <section className="al-section"><header><h2>Folders</h2><span>{scopeFolders.length}</span></header><div className={`al-folder-grid ${dense ? "dense" : ""}`}>{scopeFolders.map((folder) => <FolderCard key={folder.id} folder={folder} files={files.filter((file) => file.folderId === folder.id)} folders={folders} view={view} selected={selected.has(folder.id)} onSelect={() => toggleSelected(folder.id)} onDetails={() => setDetails(folder)} onOpen={() => setFolderId(folder.id)} />)}</div></section>}
    <section className="al-section"><header><h2>Files</h2><span>{scopeFiles.length}</span></header><div className={`al-file-grid ${dense ? "dense" : ""}`}>{scopeFiles.map((file) => <FileCard key={file.id} file={file} view={view} folders={folders} selected={selected.has(file.id)} onSelect={() => toggleSelected(file.id)} onDetails={() => setDetails(file)} onPreview={() => setPreview(file)} />)}{!scopeFiles.length && !scopeFolders.length && <div className="al-empty"><Archive /><strong>This location is empty</strong><span>Upload standalone files or organize them in a folder.</span><button onClick={() => setDialog("upload")}>Upload files</button></div>}</div></section>
    {dialog === "folder" && <FolderDialog view={view} folders={folders} defaultProjectId={projectId} defaultClientId={clientId} parentFolderId={folderId} close={() => setDialog(null)} />}
    {dialog === "upload" && <UploadDialog view={view} folders={folders} defaultProjectId={projectId} defaultClientId={clientId} currentFolderId={folderId} close={() => setDialog(null)} />}
    {preview && <PreviewDialog file={preview} close={() => setPreview(null)} />}
    {details && <DetailsDialog entity={details} view={view} close={() => setDetails(null)} />}
  </div>;
}

function FolderCard({ folder, files, folders, view, selected, onSelect, onDetails, onOpen }: { folder: LibraryFolder; files: LibraryFile[]; folders: LibraryFolder[]; view?: FilesView; selected: boolean; onSelect: () => void; onDetails: () => void; onOpen: () => void }) { return <article className={`al-folder-card ${selected ? "selected" : ""}`}><label className="al-select"><input type="checkbox" checked={selected} onChange={onSelect} aria-label={`Select ${folder.name}`} /></label><button className="al-folder-preview" onClick={onOpen}>{[...files.slice(0, 4), ...Array(Math.max(0, 4 - files.length)).fill(null)].map((file, index) => <Preview key={file?.id ?? index} file={file} />)}</button><footer><button onClick={onOpen}><strong>{folder.name}</strong><small>{files.length + folders.filter((item) => item.parentFolderId === folder.id).length} items · {relationLabel(folder, view)}</small></button><ContextMenu entity={folder} folders={folders} folderFiles={files} view={view} onOpen={onOpen} onDetails={onDetails} /></footer></article>; }
function FileCard({ file, folders, view, selected, onSelect, onDetails, onPreview }: { file: LibraryFile; folders: LibraryFolder[]; view?: FilesView; selected: boolean; onSelect: () => void; onDetails: () => void; onPreview: () => void }) { return <article className={`al-file-card ${selected ? "selected" : ""}`}><label className="al-select"><input type="checkbox" checked={selected} onChange={onSelect} aria-label={`Select ${file.name}`} /></label><button className="al-file-preview" onClick={onPreview}><Preview file={file} large /><i><Play /></i></button><div><KindIcon kind={file.kind} /><span><strong>{file.name}</strong><small>{formatSize(file.size)} · {relationLabel(file, view)}</small></span><ContextMenu entity={file} folders={folders} view={view} onPreview={onPreview} onDetails={onDetails} /></div></article>; }
function Preview({ file, large = false }: { file: LibraryFile | null; large?: boolean }) { if (!file) return <span className="al-preview-blank" />; if (file.preview) return <span className="al-preview-image" style={{ backgroundImage: `url(${file.preview})` }} />; return <span className={`al-kind-preview ${file.kind} ${large ? "large" : ""}`}><KindIcon kind={file.kind} />{file.kind === "audio" && <i><b /><b /><b /><b /><b /></i>}</span>; }
function KindIcon({ kind }: { kind: LibraryKind }) { const Icon = kind === "video" ? Film : kind === "audio" ? AudioLines : kind === "image" ? ImageIcon : kind === "document" ? FileText : kind === "source" ? FileImage : File; return <Icon />; }

function ContextMenu({ entity, folders, folderFiles = [], view, onPreview, onOpen, onDetails }: { entity: LibraryFile | LibraryFolder; folders: LibraryFolder[]; folderFiles?: LibraryFile[]; view?: FilesView; onPreview?: () => void; onOpen?: () => void; onDetails?: () => void }) { const isFile = "kind" in entity; const mutate = (action: string) => { if (action === "preview") return onPreview?.(); if (action === "open") return onOpen?.(); if (action === "details") return onDetails?.(); if (action === "download" && isFile && entity.url) { window.location.assign(entity.url); return; } if (action === "download-folder" && !isFile) { const blob = new Blob([folderFiles.map((file) => `${file.name}\t${file.mimeType}\t${file.size}`).join("\n")], { type: "text/plain" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${entity.name}-manifest.txt`; link.click(); URL.revokeObjectURL(link.href); return; } if (action === "delete") { if (!confirm(`Delete ${entity.name}?`)) return; updateLibrary((state) => deleteLibraryEntities(state, new Set([entity.id]))); return; } const name = action === "rename" ? prompt("New name", entity.name)?.trim() : null; if (action === "rename" && name) updateLibrary((state) => ({ ...state, folders: isFile ? state.folders : upsert(state.folders, { ...entity, name } as LibraryFolder), files: isFile ? upsert(state.files, { ...entity, name } as LibraryFile) : state.files })); };
  return <details className="al-menu"><summary aria-label={`Actions for ${entity.name}`}><Ellipsis /></summary><div>{!isFile && <button onClick={() => mutate("open")}>Open</button>}{isFile && <button onClick={() => mutate("preview")}>Preview</button>}<button onClick={() => mutate("details")}><Info />Details</button><button onClick={() => mutate("rename")}><Pencil />Rename</button><AssignmentMenu entity={entity} folders={folders} view={view} />{isFile && entity.url && <button onClick={() => mutate("download")}><Download />Download</button>}{!isFile && <button onClick={() => mutate("download-folder")}><Download />Download manifest</button>}<button className="danger" onClick={() => mutate("delete")}><Trash2 />Delete</button></div></details>; }
function AssignmentMenu({ entity, folders, view }: { entity: LibraryFile | LibraryFolder; folders: LibraryFolder[]; view?: FilesView }) { const isFile = "kind" in entity; const blocked = isFile ? new Set<string>() : descendantFolderIds(folders, entity.id); const set = (clientId: string | null, projectId: string | null, folderId?: string | null) => updateLibrary((state) => isFile ? ({ ...state, files: upsert(state.files, { ...entity, clientId, projectId, ...(folderId !== undefined ? { folderId } : {}) } as LibraryFile) }) : assignFolderTree({ ...state, folders: upsert(state.folders, entity as LibraryFolder) }, entity as LibraryFolder, clientId, projectId, folderId ?? null)); return <details><summary><Move />Move / assign</summary><div className="al-submenu"><button onClick={() => set(null, null, null)}>Root / unassigned</button>{view?.groups.map((group) => <button key={group.projectId} onClick={() => set(group.clientId, group.projectId, null)}>{group.projectName}</button>)}{folders.filter((folder) => folder.id !== entity.id && !blocked.has(folder.id)).map((folder) => <button key={folder.id} onClick={() => set(folder.clientId, folder.projectId, folder.id)}>↳ {folder.name}</button>)}</div></details>; }

function FolderDialog({ view, folders, defaultProjectId, defaultClientId, parentFolderId, close }: { view?: FilesView; folders: LibraryFolder[]; defaultProjectId: string | null; defaultClientId: string | null; parentFolderId: string | null; close: () => void }) { const [client, setClient] = useState(defaultClientId ?? ""); const [selectedProject, setSelectedProject] = useState(defaultProjectId ?? ""); const projects = (view?.groups ?? []).filter((group) => !client || group.clientId === client); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget), project = String(data.get("project") || selectedProject || "") || null; const projectRow = view?.groups.find((item) => item.projectId === project); updateLibrary((state) => ({ ...state, folders: [...state.folders, { id: newId("folder"), name: String(data.get("name")), clientId: (projectRow?.clientId ?? client) || null, projectId: project, parentFolderId, createdAt: new Date().toISOString(), createdBy: "You" }] })); close(); }; return <Modal title="Create folder" close={close}><form onSubmit={submit} className="al-form"><label>Folder name<input name="name" required autoFocus placeholder="Footage" /></label><RelationFields view={view} projects={projects} client={client} setClient={setClient} selectedProject={selectedProject} setProject={setSelectedProject} /><label>Inside folder<select name="parent" value={parentFolderId ?? ""} disabled><option value="">Root Files area</option>{folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label><button>Create folder</button></form></Modal>; }
function UploadDialog({ view, folders, defaultProjectId, defaultClientId, currentFolderId, close }: { view?: FilesView; folders: LibraryFolder[]; defaultProjectId: string | null; defaultClientId: string | null; currentFolderId: string | null; close: () => void }) {
  const [client, setClient] = useState(defaultClientId ?? ""); const [selectedProject, setSelectedProject] = useState(defaultProjectId ?? ""); const [uploads, setUploads] = useState<File[]>([]); const [dragging, setDragging] = useState(false);
  const projects = (view?.groups ?? []).filter((group) => !client || group.clientId === client); const availableFolders = folders.filter((folder) => !selectedProject || folder.projectId === selectedProject); const stage = (items: FileList | null) => setUploads(items ? Array.from(items).filter((file) => file.size > 0) : []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!uploads.length) return; const data = new FormData(event.currentTarget), project = String(data.get("project") || selectedProject || "") || null, folder = String(data.get("folder") || currentFolderId || "") || null, projectRow = view?.groups.find((item) => item.projectId === project); const items = await Promise.all(uploads.map(async (file): Promise<LibraryFile> => ({ id: newId("file"), name: file.name, kind: kindFor(file), mimeType: file.type || "application/octet-stream", size: file.size, url: URL.createObjectURL(file), preview: file.type.startsWith("image/") && file.size <= 1_000_000 ? await dataUrl(file) : null, uploadedBy: "You", uploadedAt: new Date().toISOString(), folderId: folder, clientId: (projectRow?.clientId ?? client) || null, projectId: project }))); updateLibrary((state) => ({ ...state, files: [...state.files, ...items] })); close(); };
  return <Modal title="Upload files" close={close}><form onSubmit={submit} className="al-form"><label className={`al-drop ${dragging ? "dragging" : ""}`} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); stage(event.dataTransfer.files); }}><Upload /><strong>Drop files here or browse</strong><span>Video, audio, images, documents, source files, or anything else</span><input name="files" type="file" multiple onChange={(event) => stage(event.target.files)} /></label>{uploads.length > 0 && <div className="al-upload-list"><strong>{uploads.length} file{uploads.length === 1 ? "" : "s"} ready</strong>{uploads.map((file) => <span key={`${file.name}-${file.lastModified}`}><KindIcon kind={kindFor(file)} />{file.name}<small>{formatSize(file.size)}</small></span>)}</div>}<RelationFields view={view} projects={projects} client={client} setClient={setClient} selectedProject={selectedProject} setProject={setSelectedProject} /><label>Folder (optional)<select name="folder" defaultValue={currentFolderId ?? ""}><option value="">Root Files area</option>{availableFolders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label><button disabled={!uploads.length}>Upload {uploads.length || ""} file{uploads.length === 1 ? "" : "s"}</button></form></Modal>;
}
function RelationFields({ view, projects, client, setClient, selectedProject, setProject }: { view?: FilesView; projects: FilesView["groups"]; client: string; setClient: (id: string) => void; selectedProject: string; setProject: (id: string) => void }) { return <div className="al-relations"><label>Client (optional)<select value={client} onChange={(event) => { setClient(event.target.value); setProject(""); }}><option value="">No client</option>{view?.clients.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Project (optional)<select name="project" value={selectedProject} onChange={(event) => setProject(event.target.value)}><option value="">No project</option>{projects.map((item) => <option key={item.projectId} value={item.projectId}>{item.projectName}</option>)}</select></label></div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="al-modal"><button className="al-backdrop" onClick={close} aria-label="Close" /><section><header><h2>{title}</h2><button onClick={close}><X /></button></header>{children}</section></div>; }
function PreviewDialog({ file, close }: { file: LibraryFile; close: () => void }) { return <Modal title={file.name} close={close}><div className="al-full-preview">{file.preview ? <NextImage src={file.preview} alt={file.name} width={1200} height={800} unoptimized /> : file.url && file.kind === "video" ? <video src={file.url} controls /> : file.url && file.kind === "audio" ? <audio src={file.url} controls /> : <Preview file={file} large />}<p>{file.mimeType} · {formatSize(file.size)} · uploaded {new Date(file.uploadedAt).toLocaleString()}</p></div></Modal>; }
function DetailsDialog({ entity, view, close }: { entity: LibraryFile | LibraryFolder; view?: FilesView; close: () => void }) { const isFile = "kind" in entity; const rows = isFile ? [["Type", entity.kind], ["Format", entity.mimeType], ["Size", formatSize(entity.size)], ["Uploaded by", entity.uploadedBy], ["Uploaded", new Date(entity.uploadedAt).toLocaleString()], ["Relationship", relationLabel(entity, view)]] : [["Type", "Folder"], ["Created by", entity.createdBy], ["Created", new Date(entity.createdAt).toLocaleString()], ["Relationship", relationLabel(entity, view)]]; return <Modal title="Asset details" close={close}><div className="al-details"><div><KindIcon kind={isFile ? entity.kind : "other"} /><h3>{entity.name}</h3></div><dl>{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div></Modal>; }
function merge<T extends { id: string }>(base: T[], overrides: T[]): T[] { const map = new Map(base.map((item) => [item.id, item])); overrides.forEach((item) => map.set(item.id, item)); return [...map.values()]; }
function upsert<T extends { id: string }>(items: T[], item: T): T[] { return items.some((candidate) => candidate.id === item.id) ? items.map((candidate) => candidate.id === item.id ? item : candidate) : [...items, item]; }
function folderTrail(folder: LibraryFolder | null, folders: LibraryFolder[]): LibraryFolder[] { const result: LibraryFolder[] = []; let item = folder; while (item) { result.unshift(item); item = folders.find((candidate) => candidate.id === item!.parentFolderId) ?? null; } return result; }
const matches = (name: string, query: string) => name.toLowerCase().includes(query.trim().toLowerCase());
const matchesRelation = (entity: { clientId: string | null; projectId: string | null }, client: string, project: string) => (!client || entity.clientId === client) && (!project || entity.projectId === project);
function sortFolders(items: LibraryFolder[], sort: "newest" | "name" | "size") { return [...items].sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : b.createdAt.localeCompare(a.createdAt)); }
function sortFiles(items: LibraryFile[], sort: "newest" | "name" | "size") { return [...items].sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "size" ? b.size - a.size : b.uploadedAt.localeCompare(a.uploadedAt)); }
const formatSize = (bytes: number) => bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : bytes < 1073741824 ? `${(bytes / 1048576).toFixed(1)} MB` : `${(bytes / 1073741824).toFixed(1)} GB`;
function mimeKind(mime: string, name: string): LibraryKind { return kindFor({ type: mime, name } as File); }
function dataUrl(file: File) { return new Promise<string>((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => resolve(""); reader.readAsDataURL(file); }); }
function relationLabel(entity: { clientId: string | null; projectId: string | null }, view?: FilesView) { const project = view?.groups.find((item) => item.projectId === entity.projectId); const client = view?.clients.find((item) => item.id === (entity.clientId ?? project?.clientId)); return [client?.name, project?.projectName].filter(Boolean).join(" / ") || "Unassigned"; }
