"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { Download, File, FilePlus2, Folder, Search, Trash2, TriangleAlert, Upload, X } from "lucide-react";
import type { FilesView } from "@/lib/files-view";

const csrf = () => decodeURIComponent(document.cookie.split("; ").find((item) => item.startsWith("csrftoken="))?.slice(10) ?? "");

export function FilesBrowser({ view }: { view: FilesView }) {
  const router = useRouter();
  const [query, setQuery] = useState(""); const [projectId, setProjectId] = useState<string | null>(null);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const files = view.groups.flatMap((group) => group.files.map((file) => ({ ...file, projectName: group.projectName, folderName: group.folders.find((folder) => folder.id === file.folder_id)?.name })))
    .filter((file) => `${file.file.name} ${file.projectName} ${file.folderName ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!view.workspaceId || !projectId) return; setBusy(true); setError(""); const response = await fetch(`/api/workspaces/${view.workspaceId}/projects/${projectId}/files/`, { method: "POST", body: new FormData(event.currentTarget), credentials: "include", headers: { "X-CSRFToken": csrf() } }); if (!response.ok) { setError((await response.json().catch(() => null) as { detail?: string } | null)?.detail || `Upload failed (${response.status}).`); setBusy(false); return; } setProjectId(null); setBusy(false); router.refresh(); }
  async function remove(fileId: string, itemProjectId: string, name: string) { if (!view.workspaceId || !confirm(`Delete ${name}?`)) return; setBusy(true); setError(""); const response = await fetch(`/api/workspaces/${view.workspaceId}/projects/${itemProjectId}/files/${fileId}/`, { method: "DELETE", credentials: "include", headers: { "X-CSRFToken": csrf() } }); if (!response.ok) setError((await response.json().catch(() => null) as { detail?: string } | null)?.detail || `Delete failed (${response.status}).`); else router.refresh(); setBusy(false); }
  return <div className="files-page">{view.notice && <p className="files-notice"><TriangleAlert />{view.notice}</p>}{error && <p className="form-error">{error}</p>}<header><div><p className="eyebrow">Asset library</p><h1>Files</h1><p>Documents and production files across every project.</p></div><button onClick={() => setProjectId(view.groups[0]?.projectId ?? null)} disabled={!view.groups.length}><FilePlus2 />Upload file</button></header><div className="files-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search files, projects, and folders…" /></div><section className="files-table"><div className="files-table-head"><span>Name</span><span>Project</span><span>Location</span><span>Size</span><span>Status</span><span>Actions</span></div>{files.map((item) => <article key={item.id}><File /><strong>{item.file.name}</strong><span>{item.projectName}</span><span><Folder />{item.folderName ?? "Project root"}</span><span>{size(item.file.size_bytes)}</span><b>{item.file.status.toLowerCase()}</b><div className="file-actions">{item.file.status === "READY" && view.workspaceId && <a href={`/api/workspaces/${view.workspaceId}/projects/${item.project_id}/files/${item.id}/download/`} aria-label={`Download ${item.file.name}`}><Download /></a>}<button disabled={busy} onClick={() => void remove(item.id, item.project_id, item.file.name)} aria-label={`Delete ${item.file.name}`}><Trash2 /></button></div></article>)}{!files.length && <p className="files-empty">No project files match this view.</p>}</section>{projectId && <div className="files-modal"><button className="files-backdrop" onClick={() => setProjectId(null)} aria-label="Close" /><form onSubmit={upload}><header><h2>Upload project file</h2><button type="button" onClick={() => setProjectId(null)}><X /></button></header><label>Project<select value={projectId} onChange={(event) => setProjectId(event.target.value)}>{view.groups.map((group) => <option key={group.projectId} value={group.projectId}>{group.projectName}</option>)}</select></label><label>Folder<select name="folder_id"><option value="">Project root</option>{view.groups.find((group) => group.projectId === projectId)?.folders.map((folder) => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label><label className="files-drop"><Upload /><span>Select a file</span><input name="file" type="file" required /></label>{error && <p className="form-error">{error}</p>}<button className="files-submit" disabled={busy}>{busy ? "Uploading…" : "Upload file"}</button></form></div>}</div>;
}
function size(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1048576).toFixed(1)} MB`; }
