"use client";

import { useActionState, useEffect, useState, useTransition } from "react";
import { Building2, Copy, Globe2, Mail, MapPin, Pencil, Plus, Trash2, TriangleAlert, UserPlus, Users, X } from "lucide-react";
import type { ClientCard, ClientsView } from "@/lib/clients-view";
import { addClientMemberAction, archiveClientAction, createClientAction, inviteClientMemberAction, removeClientMemberAction, revokeClientInviteAction, updateClientAction, type ClientActionState, type ClientInviteState } from "./actions";

const initial: ClientActionState = { error: null, message: null };
const inviteInitial: ClientInviteState = { error: null, message: null };
export function ClientsPanel({ view, focusId = null }: { view: ClientsView; focusId?: string | null }) {
  const [edit, setEdit] = useState<"new" | ClientCard | null>(null); const [manage, setManage] = useState<ClientCard | null>(null);
  const [error, setError] = useState(""); const [archiving, startArchive] = useTransition();

  // Bring the linked card into view. Guarded on the element existing, because the id can
  // name a client this account can no longer see.
  useEffect(() => {
    if (!focusId) return;
    document.getElementById(`client-${focusId}`)?.scrollIntoView({ behavior: "smooth", block: "center" });
  }, [focusId]);

  return <div className="clients-page">{view.notice && <p className="clients-notice"><TriangleAlert />{view.notice}</p>}<header><div><p className="eyebrow">Relationship directory</p><h1>Clients</h1><p>Contact details and active campaigns for {view.workspaceName}.</p></div><button onClick={() => setEdit("new")} disabled={!view.workspaceId}><Plus />New client</button></header>{error && <p className="form-error">{error}</p>}<section className="clients-grid">{view.clients.map((client) => <article key={client.id} id={`client-${client.id}`} className={client.id === focusId ? "is-focused" : undefined}><div className="client-card-head"><span><Building2 /></span><div><h2>{client.name}</h2><small>{client.projects.length} projects · {client.members.length} members</small></div><button onClick={() => setEdit(client)} aria-label={`Edit ${client.name}`}><Pencil /></button></div><p>{client.description || "No client description yet."}</p><dl>{client.email && <div><Mail /><a href={`mailto:${client.email}`}>{client.email}</a></div>}{client.website && <div><Globe2 /><a href={client.website} target="_blank" rel="noreferrer">{client.website}</a></div>}{client.city && <div><MapPin /><span>{[client.city, client.country_code].filter(Boolean).join(", ")}</span></div>}</dl><div className="client-projects">{client.projects.slice(0, 4).map((project) => <span key={project.id}>{project.name}</span>)}{!client.projects.length && <small>No campaigns assigned</small>}</div><div className="client-card-actions"><button onClick={() => setManage(client)}><Users />Members & invites</button><button className="client-archive" disabled={archiving} onClick={() => startArchive(async () => { if (!confirm(`Archive ${client.name}?`)) return; const result = await archiveClientAction(client.id); if (result.error) setError(result.error); })}><Trash2 />Archive</button></div></article>)}{!view.clients.length && <p className="clients-empty">No clients yet. Create the first relationship record.</p>}</section>{edit && <ClientDialog client={edit === "new" ? null : edit} close={() => setEdit(null)} />}{manage && <ClientAccessDialog client={manage} close={() => setManage(null)} />}</div>;
}

function ClientDialog({ client, close }: { client: ClientCard | null; close: () => void }) { const [state, action, pending] = useActionState(client ? updateClientAction : createClientAction, initial); return <div className="client-modal"><button className="client-backdrop" onClick={close} aria-label="Close" /><form action={action}><header><h2>{client ? `Edit ${client.name}` : "Create client"}</h2><button type="button" onClick={close}><X /></button></header>{client && <input type="hidden" name="client_id" value={client.id} />}<div className="client-fields"><label>Name<input name="name" defaultValue={client?.name ?? ""} required /></label><label>Email<input name="email" type="email" defaultValue={client?.email ?? ""} /></label><label>Website<input name="website" type="url" defaultValue={client?.website ?? ""} placeholder="https://" /></label><label>Phone<input name="phone" defaultValue={client?.phone ?? ""} /></label><label>City<input name="city" defaultValue={client?.city ?? ""} /></label><label>Country code<input name="country_code" maxLength={2} defaultValue={client?.country_code ?? ""} /></label></div><label>Description<textarea name="description" rows={4} defaultValue={client?.description ?? ""} /></label>{state.error && <p className="form-error">{state.error}</p>}{state.message && <p className="client-success">{state.message}</p>}<button className="client-save" disabled={pending}>{pending ? "Saving…" : "Save client"}</button></form></div>; }

function ClientAccessDialog({ client, close }: { client: ClientCard; close: () => void }) {
  const [memberState, memberAction, adding] = useActionState(addClientMemberAction, initial); const [inviteState, inviteAction, inviting] = useActionState(inviteClientMemberAction, inviteInitial); const [error, setError] = useState(""); const [, mutate] = useTransition();
  return <div className="client-modal"><button className="client-backdrop" onClick={close} aria-label="Close" /><section className="client-access"><header><h2>{client.name} access</h2><button onClick={close}><X /></button></header><h3>Members</h3><form action={memberAction} className="client-inline"><input type="hidden" name="client_id" value={client.id} /><input name="email" type="email" placeholder="Existing account email" required /><input name="title" placeholder="Title" /><button disabled={adding}><UserPlus />Add</button></form>{memberState.error && <p className="form-error">{memberState.error}</p>}<ul>{client.members.map((member) => <li key={member.id}><span><strong>{member.user.first_name || member.user.email}</strong><small>{member.title || member.user.email}</small></span><button onClick={() => mutate(async () => { const result = await removeClientMemberAction(client.id, member.id); if (result.error) setError(result.error); })}>Remove</button></li>)}</ul><h3>Invitations</h3><form action={inviteAction} className="client-inline"><input type="hidden" name="client_id" value={client.id} /><input name="email" type="email" placeholder="Email (blank for link)" /><input name="label" placeholder="Label" /><input name="expires_in_days" type="number" min="1" max="90" defaultValue="14" /><button disabled={inviting}>Invite</button></form>{inviteState.error && <p className="form-error">{inviteState.error}</p>}{inviteState.token && <button className="client-token" onClick={() => navigator.clipboard.writeText(inviteState.token!)}><Copy />Copy one-time token</button>}<ul>{client.invites.map((invite) => <li key={invite.id}><span><strong>{invite.recipient_email || invite.label || "Share link"}</strong><small>{invite.revoked_at ? "Revoked" : `${invite.use_count} uses · expires ${new Date(invite.expires_at).toLocaleDateString()}`}</small></span>{!invite.revoked_at && <button onClick={() => mutate(async () => { const result = await revokeClientInviteAction(client.id, invite.id); if (result.error) setError(result.error); })}>Revoke</button>}</li>)}</ul>{error && <p className="form-error">{error}</p>}</section></div>;
}
