# Generated by Django 4.2.27 on 2026-08-31 18:11

import app.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', app.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('end_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'annotations',
            },
        ),
        migrations.CreateModel(
            name='ClientTeam',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state_region', models.CharField(blank=True, max_length=150, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'client_teams',
            },
        ),
        migrations.CreateModel(
            name='ClientTeamInvite',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('invite_type', models.CharField(choices=[('EMAIL', 'Email'), ('LINK', 'Link')], max_length=20)),
                ('recipient_email', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('client_team', models.ForeignKey(db_column='client_team_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.clientteam')),
            ],
            options={
                'db_table': 'client_team_invites',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=1024)),
                ('original_name', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=512, null=True)),
                ('checksum_algorithm', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='GuestInvite',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'guest_invites',
            },
        ),
        migrations.CreateModel(
            name='GuestReviewAccess',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('guest_invite', models.ForeignKey(db_column='guest_invite_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestinvite')),
            ],
            options={
                'db_table': 'guest_review_access',
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=255)),
                ('access_key_hash', models.CharField(max_length=255, unique=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'guest_sessions',
            },
        ),
        migrations.CreateModel(
            name='MediaVersion',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('allow_download', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_DELETION', 'Pending Deletion')], default='ACTIVE', max_length=30)),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('original_file', models.ForeignKey(db_column='original_file_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.file')),
            ],
            options={
                'db_table': 'media_versions',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('PENDING_DELETION', 'Pending Deletion')], default='DRAFT', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('next_media_version_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('end_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('author_guest_session', models.ForeignKey(blank=True, db_column='author_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession')),
                ('author_user', models.ForeignKey(blank=True, db_column='author_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by_guest_session', models.ForeignKey(blank=True, db_column='deleted_by_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession')),
                ('deleted_by_user', models.ForeignKey(blank=True, db_column='deleted_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('media_version', models.ForeignKey(db_column='media_version_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.mediaversion')),
                ('parent_comment', models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.reviewcomment')),
                ('resolved_by_user', models.ForeignKey(blank=True, db_column='resolved_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_comments',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_stages',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('timezone', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('PENDING_DELETION', 'Pending Deletion')], default='ACTIVE', max_length=30)),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceProfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=30, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('workspace', models.OneToOneField(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'workspace_profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('principal_type', models.CharField(choices=[('USER', 'User'), ('CLIENT_TEAM', 'Client Team')], max_length=20)),
                ('project_access_mode', models.CharField(choices=[('ALL', 'All'), ('SELECTED', 'Selected')], default='SELECTED', max_length=20)),
                ('is_primary_owner', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed')], max_length=20)),
                ('joined_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('client_team', models.ForeignKey(blank=True, db_column='client_team_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.clientteam')),
                ('role', models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.role')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'workspace_memberships',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageStatus',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow_stage', models.ForeignKey(db_column='workflow_stage_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workflowstage')),
            ],
            options={
                'db_table': 'workflow_stage_statuses',
            },
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PAST_DUE', 'Past Due')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('attached_at', models.DateTimeField()),
                ('attached_by_workspace_membership', models.ForeignKey(db_column='attached_by_workspace_membership_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership')),
                ('file', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.file')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.task')),
            ],
            options={
                'db_table': 'task_attachments',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField()),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.task')),
                ('workspace_membership', models.ForeignKey(db_column='workspace_membership_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership')),
            ],
            options={
                'db_table': 'task_assignees',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='created_by_workspace_membership',
            field=models.ForeignKey(db_column='created_by_workspace_membership_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.CreateModel(
            name='StorageBackend',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('provider', models.CharField(max_length=100)),
                ('config', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'storage_backends',
                'indexes': [models.Index(fields=['provider'], name='storage_bac_provide_db9496_idx'), models.Index(fields=['status'], name='storage_bac_status_c9479f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission_key', models.CharField(max_length=100)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.role')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.CreateModel(
            name='ReviewCommentRevision',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('edited_by_guest_session', models.ForeignKey(blank=True, db_column='edited_by_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession')),
                ('edited_by_user', models.ForeignKey(blank=True, db_column='edited_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review_comment', models.ForeignKey(db_column='review_comment_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.reviewcomment')),
            ],
            options={
                'db_table': 'review_comment_revisions',
            },
        ),
        migrations.CreateModel(
            name='ReviewCommentContent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('FILE', 'File')], max_length=20)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.file')),
                ('review_comment', models.ForeignKey(db_column='review_comment_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.reviewcomment')),
            ],
            options={
                'db_table': 'review_comment_contents',
            },
        ),
        migrations.CreateModel(
            name='ResourceAccess',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project')),
                ('workspace_membership', models.ForeignKey(db_column='workspace_membership_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership')),
            ],
            options={
                'db_table': 'resource_access',
            },
        ),
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by_workspace_membership', models.ForeignKey(db_column='created_by_workspace_membership_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership')),
                ('parent_folder', models.ForeignKey(blank=True, db_column='parent_folder_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.projectfolder')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project')),
            ],
            options={
                'db_table': 'project_folders',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('added_by_workspace_membership', models.ForeignKey(db_column='added_by_workspace_membership_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership')),
                ('file', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.file')),
                ('folder', models.ForeignKey(blank=True, db_column='folder_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.projectfolder')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project')),
            ],
            options={
                'db_table': 'project_files',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='OAuthIdentity',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google')], max_length=20)),
                ('provider_subject', models.CharField(max_length=255)),
                ('provider_email', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_email_verified', models.BooleanField(default=False)),
                ('provider_first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_avatar_url', models.TextField(blank=True, null=True)),
                ('profile_metadata', models.JSONField(blank=True, null=True)),
                ('linked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_identities',
            },
        ),
        migrations.CreateModel(
            name='MediaVersionStageEntry',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('snapshot', models.JSONField()),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('changed_by_user', models.ForeignKey(db_column='changed_by_user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('media_version', models.ForeignKey(db_column='media_version_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.mediaversion')),
                ('workflow_stage', models.ForeignKey(blank=True, db_column='workflow_stage_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workflowstage')),
                ('workflow_stage_status', models.ForeignKey(blank=True, db_column='workflow_stage_status_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workflowstagestatus')),
            ],
            options={
                'db_table': 'media_version_stage_entries',
            },
        ),
        migrations.AddField(
            model_name='mediaversion',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project'),
        ),
        migrations.AddField(
            model_name='guestsession',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.CreateModel(
            name='GuestReviewAccessPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('guest_review_access', models.ForeignKey(db_column='guest_review_access_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestreviewaccess')),
            ],
            options={
                'db_table': 'guest_review_access_permissions',
            },
        ),
        migrations.AddField(
            model_name='guestreviewaccess',
            name='guest_session',
            field=models.ForeignKey(db_column='guest_session_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession'),
        ),
        migrations.AddField(
            model_name='guestreviewaccess',
            name='revoked_by_workspace_membership',
            field=models.ForeignKey(blank=True, db_column='revoked_by_workspace_membership_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership'),
        ),
        migrations.CreateModel(
            name='GuestInvitePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('guest_invite', models.ForeignKey(db_column='guest_invite_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestinvite')),
            ],
            options={
                'db_table': 'guest_invite_permissions',
            },
        ),
        migrations.AddField(
            model_name='guestinvite',
            name='created_by_workspace_membership',
            field=models.ForeignKey(db_column='created_by_workspace_membership_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership'),
        ),
        migrations.AddField(
            model_name='guestinvite',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project'),
        ),
        migrations.AddField(
            model_name='guestinvite',
            name='revoked_by_workspace_membership',
            field=models.ForeignKey(blank=True, db_column='revoked_by_workspace_membership_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership'),
        ),
        migrations.CreateModel(
            name='FileVariant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=1024)),
                ('original_name', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=512, null=True)),
                ('checksum_algorithm', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('file', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.file')),
                ('storage_backend', models.ForeignKey(db_column='storage_backend_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.storagebackend')),
            ],
            options={
                'db_table': 'file_variants',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='storage_backend',
            field=models.ForeignKey(db_column='storage_backend_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.storagebackend'),
        ),
        migrations.CreateModel(
            name='ClientTeamMember',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('added_by_workspace_membership', models.ForeignKey(blank=True, db_column='added_by_workspace_membership_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership')),
                ('client_team', models.ForeignKey(db_column='client_team_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.clientteam')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_team_members',
            },
        ),
        migrations.CreateModel(
            name='ClientTeamInviteAcceptance',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField()),
                ('client_team_member', models.ForeignKey(db_column='client_team_member_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.clientteammember')),
                ('invite', models.ForeignKey(db_column='invite_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.clientteaminvite')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_team_invite_acceptances',
            },
        ),
        migrations.AddField(
            model_name='clientteaminvite',
            name='created_by_workspace_membership',
            field=models.ForeignKey(blank=True, db_column='created_by_workspace_membership_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership'),
        ),
        migrations.AddField(
            model_name='clientteaminvite',
            name='revoked_by_workspace_membership',
            field=models.ForeignKey(blank=True, db_column='revoked_by_workspace_membership_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership'),
        ),
        migrations.AddField(
            model_name='clientteam',
            name='created_by_workspace_membership',
            field=models.ForeignKey(blank=True, db_column='created_by_workspace_membership_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership'),
        ),
        migrations.AddField(
            model_name='clientteam',
            name='logo_file',
            field=models.ForeignKey(blank=True, db_column='logo_file_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.file'),
        ),
        migrations.AddField(
            model_name='clientteam',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('GUEST', 'Guest'), ('SYSTEM', 'System')], max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('actor_guest_session', models.ForeignKey(blank=True, db_column='actor_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession')),
                ('actor_user', models.ForeignKey(blank=True, db_column='actor_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, db_column='workspace_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='AnnotationRevision',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('annotation', models.ForeignKey(db_column='annotation_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.annotation')),
                ('edited_by_guest_session', models.ForeignKey(blank=True, db_column='edited_by_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession')),
                ('edited_by_user', models.ForeignKey(blank=True, db_column='edited_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annotation_revisions',
            },
        ),
        migrations.CreateModel(
            name='AnnotationElement',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('element_type', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('style', models.JSONField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('annotation', models.ForeignKey(db_column='annotation_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.annotation')),
            ],
            options={
                'db_table': 'annotation_elements',
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='author_guest_session',
            field=models.ForeignKey(blank=True, db_column='author_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='author_user',
            field=models.ForeignKey(blank=True, db_column='author_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='deleted_by_guest_session',
            field=models.ForeignKey(blank=True, db_column='deleted_by_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='deleted_by_user',
            field=models.ForeignKey(blank=True, db_column='deleted_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='media_version',
            field=models.ForeignKey(db_column='media_version_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.mediaversion'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='review_comment',
            field=models.ForeignKey(blank=True, db_column='review_comment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.reviewcomment'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace'], name='workspace_m_workspa_971f55_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['user'], name='workspace_m_user_id_84ca21_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['client_team'], name='workspace_m_client__e589e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='workspace_memberships_workspace_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('workspace', 'client_team'), name='workspace_memberships_workspace_client_team_uniq'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['created_by_user'], name='workspaces_created_0170a6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstagestatus',
            index=models.Index(fields=['workflow_stage'], name='workflow_st_workflo_d722a5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstagestatus',
            index=models.Index(fields=['sort_order'], name='workflow_st_sort_or_6ed7b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstagestatus',
            constraint=models.UniqueConstraint(fields=('workflow_stage', 'slug'), name='workflow_stage_statuses_stage_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='workflowstage',
            index=models.Index(fields=['workspace'], name='workflow_st_workspa_d054f9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstage',
            index=models.Index(fields=['sort_order'], name='workflow_st_sort_or_7d2da7_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='workflow_stages_workspace_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user'], name='user_subscr_user_id_3bc394_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['provider_subscription_id'], name='user_subscr_provide_23c9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='user_subscr_user_id_c57286_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task'], name='task_attach_task_id_637c08_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['file'], name='task_attach_file_id_06921a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['attached_by_workspace_membership'], name='task_attach_attache_a71f12_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskattachment',
            constraint=models.UniqueConstraint(fields=('task', 'file'), name='task_attachments_task_file_uniq'),
        ),
        migrations.AddIndex(
            model_name='taskassignee',
            index=models.Index(fields=['task'], name='task_assign_task_id_39473c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignee',
            index=models.Index(fields=['workspace_membership'], name='task_assign_workspa_71baa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskassignee',
            constraint=models.UniqueConstraint(fields=('task', 'workspace_membership'), name='task_assignees_task_membership_uniq'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace'], name='tasks_workspa_d4521b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='tasks_project_f1bd77_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by_workspace_membership'], name='tasks_created_930cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_status_031d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_priorit_a9efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_at'], name='tasks_due_at_22323a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deleted_at'], name='tasks_deleted_1d9a30_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'status'], name='tasks_workspa_40553c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_project_fe19a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission_key'), name='role_permissions_role_permission_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='roles_workspace_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='reviewcommentrevision',
            index=models.Index(fields=['review_comment'], name='review_comm_review__61d5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcommentrevision',
            index=models.Index(fields=['edited_by_user'], name='review_comm_edited__a61927_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcommentrevision',
            index=models.Index(fields=['edited_by_guest_session'], name='review_comm_edited__a2a1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcommentcontent',
            index=models.Index(fields=['review_comment'], name='review_comm_review__6f14e9_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcommentcontent',
            index=models.Index(fields=['file'], name='review_comm_file_id_2cae0b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcommentcontent',
            index=models.Index(fields=['review_comment', 'sort_order'], name='review_comm_review__cd50d9_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['media_version'], name='review_comm_media_v_5ff0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['parent_comment'], name='review_comm_parent__b89f05_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['author_user'], name='review_comm_author__ca0874_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['author_guest_session'], name='review_comm_author__27bf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['resolved'], name='review_comm_resolve_bff141_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['deleted_at'], name='review_comm_deleted_da0500_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceaccess',
            index=models.Index(fields=['project'], name='resource_ac_project_cf295d_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourceaccess',
            constraint=models.UniqueConstraint(fields=('workspace_membership', 'project'), name='resource_access_membership_project_uniq'),
        ),
        migrations.AddIndex(
            model_name='projectfolder',
            index=models.Index(fields=['project'], name='project_fol_project_d54c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfolder',
            index=models.Index(fields=['parent_folder'], name='project_fol_parent__77ccb1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfolder',
            index=models.Index(fields=['created_by_workspace_membership'], name='project_fol_created_28dd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfolder',
            index=models.Index(fields=['deleted_at'], name='project_fol_deleted_678110_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectfolder',
            constraint=models.UniqueConstraint(fields=('project', 'parent_folder', 'name'), name='project_folders_project_parent_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project'], name='project_fil_project_4db9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['folder'], name='project_fil_folder__e29257_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['file'], name='project_fil_file_id_04c041_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['added_by_workspace_membership'], name='project_fil_added_b_c95762_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['deleted_at'], name='project_fil_deleted_9043e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectfile',
            constraint=models.UniqueConstraint(fields=('project', 'file'), name='project_files_project_file_uniq'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace'], name='projects_workspa_317e49_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by_user'], name='projects_created_da988a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'created_at'], name='password_re_user_id_aa22c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='oauthidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_subject'), name='oauth_identities_provider_subject_uniq'),
        ),
        migrations.AddConstraint(
            model_name='oauthidentity',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='oauth_identities_user_provider_uniq'),
        ),
        migrations.AddIndex(
            model_name='mediaversionstageentry',
            index=models.Index(fields=['media_version'], name='media_versi_media_v_1d6bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaversionstageentry',
            index=models.Index(fields=['workflow_stage'], name='media_versi_workflo_feea05_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaversionstageentry',
            index=models.Index(fields=['workflow_stage_status'], name='media_versi_workflo_dd58a5_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaversionstageentry',
            index=models.Index(fields=['media_version', 'entered_at'], name='media_versi_media_v_d65b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaversion',
            index=models.Index(fields=['project'], name='media_versi_project_612c78_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaversion',
            index=models.Index(fields=['original_file'], name='media_versi_origina_31188a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaversion',
            index=models.Index(fields=['created_by_user'], name='media_versi_created_5e46b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='media_versions_project_version_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['workspace'], name='guest_sessi_workspa_4497d9_idx'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['workspace', 'email'], name='guest_sessi_workspa_6fd744_idx'),
        ),
        migrations.AddConstraint(
            model_name='guestreviewaccesspermission',
            constraint=models.UniqueConstraint(fields=('guest_review_access', 'permission_key'), name='guest_review_access_permissions_access_permission_uniq'),
        ),
        migrations.AddIndex(
            model_name='guestreviewaccess',
            index=models.Index(fields=['guest_invite'], name='guest_revie_guest_i_4b58e6_idx'),
        ),
        migrations.AddIndex(
            model_name='guestreviewaccess',
            index=models.Index(fields=['guest_session'], name='guest_revie_guest_s_41ca48_idx'),
        ),
        migrations.AddIndex(
            model_name='guestreviewaccess',
            index=models.Index(fields=['revoked_at'], name='guest_revie_revoked_156f9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='guestreviewaccess',
            constraint=models.UniqueConstraint(fields=('guest_session', 'guest_invite'), name='guest_review_access_session_invite_uniq'),
        ),
        migrations.AddConstraint(
            model_name='guestinvitepermission',
            constraint=models.UniqueConstraint(fields=('guest_invite', 'permission_key'), name='guest_invite_permissions_invite_permission_uniq'),
        ),
        migrations.AddIndex(
            model_name='guestinvite',
            index=models.Index(fields=['project'], name='guest_invit_project_4a7b31_idx'),
        ),
        migrations.AddIndex(
            model_name='guestinvite',
            index=models.Index(fields=['expires_at'], name='guest_invit_expires_020315_idx'),
        ),
        migrations.AddIndex(
            model_name='guestinvite',
            index=models.Index(fields=['revoked_at'], name='guest_invit_revoked_d2d924_idx'),
        ),
        migrations.AddIndex(
            model_name='filevariant',
            index=models.Index(fields=['file'], name='file_varian_file_id_06c05a_idx'),
        ),
        migrations.AddIndex(
            model_name='filevariant',
            index=models.Index(fields=['storage_backend'], name='file_varian_storage_96cbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='filevariant',
            index=models.Index(fields=['mime_type'], name='file_varian_mime_ty_950ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='filevariant',
            index=models.Index(fields=['status'], name='file_varian_status_859804_idx'),
        ),
        migrations.AddIndex(
            model_name='filevariant',
            index=models.Index(fields=['deleted_at'], name='file_varian_deleted_a99d6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='filevariant',
            constraint=models.UniqueConstraint(fields=('storage_backend', 'object_key'), name='file_variants_storage_backend_object_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['storage_backend'], name='files_storage_39f3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['mime_type'], name='files_mime_ty_5c3514_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['status'], name='files_status_179a06_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['deleted_at'], name='files_deleted_65053c_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('storage_backend', 'object_key'), name='files_storage_backend_object_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='clientteammember',
            index=models.Index(fields=['client_team'], name='client_team_client__f448fe_idx'),
        ),
        migrations.AddIndex(
            model_name='clientteammember',
            index=models.Index(fields=['user'], name='client_team_user_id_648ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientteammember',
            index=models.Index(fields=['status'], name='client_team_status_210dd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientteammember',
            constraint=models.UniqueConstraint(fields=('client_team', 'user'), name='client_team_members_team_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='clientteaminviteacceptance',
            index=models.Index(fields=['invite'], name='client_team_invite__7a5620_idx'),
        ),
        migrations.AddIndex(
            model_name='clientteaminviteacceptance',
            index=models.Index(fields=['user'], name='client_team_user_id_8d5ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientteaminviteacceptance',
            index=models.Index(fields=['client_team_member'], name='client_team_client__8f6a61_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientteaminviteacceptance',
            constraint=models.UniqueConstraint(fields=('invite', 'user'), name='client_team_invite_acceptances_invite_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='clientteaminvite',
            index=models.Index(fields=['client_team'], name='client_team_client__68f0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='clientteaminvite',
            index=models.Index(fields=['recipient_email'], name='client_team_recipie_7037a5_idx'),
        ),
        migrations.AddIndex(
            model_name='clientteaminvite',
            index=models.Index(fields=['expires_at'], name='client_team_expires_442180_idx'),
        ),
        migrations.AddIndex(
            model_name='clientteaminvite',
            index=models.Index(fields=['revoked_at'], name='client_team_revoked_3259e0_idx'),
        ),
        migrations.AddIndex(
            model_name='clientteam',
            index=models.Index(fields=['workspace'], name='client_team_workspa_8d6b74_idx'),
        ),
        migrations.AddIndex(
            model_name='clientteam',
            index=models.Index(fields=['status'], name='client_team_status_112c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['workspace', 'created_at'], name='audit_logs_workspa_bba528_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_user'], name='audit_logs_actor_u_6a2681_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_guest_session'], name='audit_logs_actor_g_a6bd99_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationrevision',
            index=models.Index(fields=['annotation'], name='annotation__annotat_f16803_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationrevision',
            index=models.Index(fields=['edited_by_user'], name='annotation__edited__0d287c_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationrevision',
            index=models.Index(fields=['edited_by_guest_session'], name='annotation__edited__4e032f_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationelement',
            index=models.Index(fields=['annotation'], name='annotation__annotat_916af8_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationelement',
            index=models.Index(fields=['element_type'], name='annotation__element_26de2d_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationelement',
            index=models.Index(fields=['annotation', 'sort_order'], name='annotation__annotat_e777e1_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['media_version'], name='annotations_media_v_437b65_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['review_comment'], name='annotations_review__5fb431_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['author_user'], name='annotations_author__a1d202_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['author_guest_session'], name='annotations_author__935564_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['deleted_at'], name='annotations_deleted_145be3_idx'),
        ),
    ]
