# Generated by Django 4.2.27 on 2026-08-31 18:35

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('author_guest_session__isnull', True), ('author_user__isnull', False)), models.Q(('author_guest_session__isnull', False), ('author_user__isnull', True)), _connector='OR'), name='annotations_exactly_one_author'),
        ),
        migrations.AddConstraint(
            model_name='mediaversionstageentry',
            constraint=models.UniqueConstraint(condition=models.Q(('exited_at__isnull', True)), fields=('media_version',), name='media_stage_entries_one_open_entry'),
        ),
        migrations.AddConstraint(
            model_name='reviewcomment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('author_guest_session__isnull', True), ('author_user__isnull', False)), models.Q(('author_guest_session__isnull', False), ('author_user__isnull', True)), _connector='OR'), name='review_comments_exactly_one_author'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_email_case_insensitive_uniq'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'PAST_DUE'])), fields=('user',), name='user_subscriptions_one_current'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('client_team__isnull', True), ('principal_type', 'USER'), ('user__isnull', False)), models.Q(('client_team__isnull', False), ('principal_type', 'CLIENT_TEAM'), ('user__isnull', True)), _connector='OR'), name='workspace_memberships_principal_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.CheckConstraint(check=models.Q(('is_primary_owner', False), models.Q(('client_team__isnull', True), ('principal_type', 'USER'), ('status', 'ACTIVE'), ('user__isnull', False)), _connector='OR'), name='workspace_memberships_owner_is_active_user'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_owner', True), ('status', 'ACTIVE')), fields=('workspace',), name='workspace_memberships_one_active_owner'),
        ),
    ]
