# Generated by Django 4.2.27 on 2026-08-31 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_annotation_annotations_exactly_one_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('project_access_mode', models.CharField(choices=[('ALL', 'All'), ('SELECTED', 'Selected')], default='ALL', max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.role')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'workspace_invites',
                'indexes': [models.Index(fields=['workspace', 'email'], name='workspace_i_workspa_df3687_idx'), models.Index(fields=['expires_at'], name='workspace_i_expires_a5e4a7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workspaceinvite',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('accepted_at__isnull', True), ('accepted_by_user__isnull', True)), models.Q(('accepted_at__isnull', False), ('accepted_by_user__isnull', False)), _connector='OR'), name='workspace_invites_acceptance_pair'),
        ),
    ]
