# Generated by Django 4.2.27 on 2026-08-31 19:07

from django.db import migrations, models
import django.db.models.functions.text


def mark_system_roles(apps, schema_editor):
    role = apps.get_model('app', 'Role')
    role.objects.filter(name__in=['Owner', 'Member']).update(is_system=True)


def unmark_system_roles(apps, schema_editor):
    role = apps.get_model('app', 'Role')
    role.objects.filter(name__in=['Owner', 'Member']).update(is_system=False)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workspaceinvite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_system_roles, unmark_system_roles),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(models.F('workspace'), django.db.models.functions.text.Lower('name'), name='roles_workspace_name_case_insensitive_uniq'),
        ),
    ]
