# Generated by Django 4.2.27 on 2026-08-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_role_is_system_and_more'),
    ]

    operations = [
    ]
