# Generated by Django 4.2.27 on 2026-08-31 19:10

import uuid

from django.db import migrations
from django.utils import timezone


def add_media_foundation(apps, schema_editor):
    role = apps.get_model('app', 'Role')
    role_permission = apps.get_model('app', 'RolePermission')
    workspace = apps.get_model('app', 'Workspace')
    workflow_stage = apps.get_model('app', 'WorkflowStage')
    now = timezone.now()

    for system_role in role.objects.filter(is_system=True, name__in=['Owner', 'Member']):
        for permission_key in ('media.create', 'media.read'):
            role_permission.objects.get_or_create(
                role=system_role,
                permission_key=permission_key,
            )

    stages = (
        ('Queued', 'queued'),
        ('In Progress', 'in-progress'),
        ('In Review', 'in-review'),
        ('Revision', 'revision'),
        ('Approval', 'approval'),
        ('Approved', 'approved'),
    )
    for existing_workspace in workspace.objects.all():
        for sort_order, (name, slug) in enumerate(stages, start=1):
            workflow_stage.objects.get_or_create(
                workspace=existing_workspace,
                slug=slug,
                defaults={
                    'id': uuid.uuid4(),
                    'name': name,
                    'sort_order': sort_order,
                    'created_by_user': existing_workspace.created_by_user,
                    'status': 'ACTIVE',
                    'created_at': now,
                    'updated_at': now,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_role_is_system_and_more'),
    ]

    operations = [
        migrations.RunPython(add_media_foundation, migrations.RunPython.noop),
    ]
