# Generated by Django 4.2.27 on 2026-09-01 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_review_attachments_annotation_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSecurityScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_scan', to='app.file')),
            ],
            options={
                'db_table': 'file_security_scans',
                'indexes': [models.Index(fields=['status', 'created_at'], name='file_securi_status_68f091_idx')],
            },
        ),
    ]
