# Generated by Django 4.2.27 on 2026-09-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_file_security_scanning'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcommentcontent',
            name='deleted_by_guest_session',
            field=models.ForeignKey(blank=True, db_column='deleted_by_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession'),
        ),
    ]
