# Generated by Django 4.2.27 on 2026-09-01

from django.db import migrations, models
import django.db.models.deletion


def add_reaction_permission(apps, schema_editor):
    role = apps.get_model('app', 'Role')
    role_permission = apps.get_model('app', 'RolePermission')
    for system_role in role.objects.filter(is_system=True, name__in=['Owner', 'Member']):
        role_permission.objects.get_or_create(
            role=system_role, permission_key='review.reaction.create'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_email_verification_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCommentReaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('emoji', models.CharField(choices=[('👍', 'Thumbs up'), ('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Surprised'), ('😢', 'Sad'), ('🎉', 'Celebrate')], max_length=16)),
                ('created_at', models.DateTimeField()),
                ('reacted_by_guest_session', models.ForeignKey(blank=True, db_column='reacted_by_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession')),
                ('reacted_by_user', models.ForeignKey(blank=True, db_column='reacted_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.user')),
                ('review_comment', models.ForeignKey(db_column='review_comment_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.reviewcomment')),
            ],
            options={
                'db_table': 'review_comment_reactions',
                'indexes': [
                    models.Index(fields=['review_comment', 'emoji'], name='review_comm_review__6e1dc1_idx'),
                    models.Index(fields=['reacted_by_user'], name='review_comm_reacted_381612_idx'),
                    models.Index(fields=['reacted_by_guest_session'], name='review_comm_reacted_904730_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(check=models.Q(models.Q(('reacted_by_guest_session__isnull', True), ('reacted_by_user__isnull', False)), models.Q(('reacted_by_guest_session__isnull', False), ('reacted_by_user__isnull', True)), _connector='OR'), name='review_reactions_exactly_one_actor'),
                    models.UniqueConstraint(condition=models.Q(('reacted_by_user__isnull', False)), fields=('review_comment', 'emoji', 'reacted_by_user'), name='review_reactions_comment_emoji_user_uniq'),
                    models.UniqueConstraint(condition=models.Q(('reacted_by_guest_session__isnull', False)), fields=('review_comment', 'emoji', 'reacted_by_guest_session'), name='review_reactions_comment_emoji_guest_uniq'),
                ],
            },
        ),
        migrations.RunPython(add_reaction_permission, migrations.RunPython.noop),
    ]
