# Generated by Django 4.2.27 on 2026-09-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_review_comment_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRetentionPolicy',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('review_file_cleanup_enabled', models.BooleanField(default=True)),
                ('review_file_retention_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('updated_by_user', models.ForeignKey(db_column='updated_by_user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.user')),
                ('workspace', models.OneToOneField(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'workspace_retention_policies',
            },
        ),
    ]
