# Generated by Django 4.2.27 on 2026-09-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_add_task_permissions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_folder__isnull', True)), fields=('project', 'name'), name='project_folders_root_name_uniq'),
        ),
    ]
