# Generated by Django 4.2.27 on 2026-09-02 22:59

from django.db import migrations, models
import django.db.models.deletion


def backfill_file_workspace(apps, schema_editor):
    File = apps.get_model('app', 'File')
    MediaVersion = apps.get_model('app', 'MediaVersion')
    ProjectFile = apps.get_model('app', 'ProjectFile')
    ReviewCommentContent = apps.get_model('app', 'ReviewCommentContent')
    TaskAttachment = apps.get_model('app', 'TaskAttachment')
    ClientTeam = apps.get_model('app', 'ClientTeam')

    for media_version in MediaVersion.objects.select_related('project').all():
        File.objects.filter(id=media_version.original_file_id, workspace__isnull=True).update(
            workspace_id=media_version.project.workspace_id,
        )
    for project_file in ProjectFile.objects.select_related('project').all():
        File.objects.filter(id=project_file.file_id, workspace__isnull=True).update(
            workspace_id=project_file.project.workspace_id,
        )
    for content in ReviewCommentContent.objects.select_related('review_comment__media_version__project').filter(
        file__isnull=False,
    ):
        File.objects.filter(id=content.file_id, workspace__isnull=True).update(
            workspace_id=content.review_comment.media_version.project.workspace_id,
        )
    for attachment in TaskAttachment.objects.select_related('task').all():
        File.objects.filter(id=attachment.file_id, workspace__isnull=True).update(
            workspace_id=attachment.task.workspace_id,
        )
    for client_team in ClientTeam.objects.filter(logo_file__isnull=False):
        File.objects.filter(id=client_team.logo_file_id, workspace__isnull=True).update(
            workspace_id=client_team.workspace_id,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_add_project_file_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.RunPython(backfill_file_workspace, noop_reverse),
        migrations.AlterField(
            model_name='file',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['workspace'], name='files_workspa_ed3822_idx'),
        ),
    ]
