# Generated by Django 4.2.27 on 2026-09-09 13:43

from django.db import migrations, models
import django.db.models.deletion


def migrate_project_links(apps, schema_editor):
    ClientTeam = apps.get_model('app', 'ClientTeam')
    Project = apps.get_model('app', 'Project')
    for team in ClientTeam.objects.order_by('created_at', 'id').iterator():
        metadata = team.metadata if isinstance(team.metadata, dict) else {}
        project_ids = metadata.get('project_ids')
        if isinstance(project_ids, list):
            Project.objects.filter(
                id__in=project_ids,
                workspace_id=team.workspace_id,
                client_team_id__isnull=True,
            ).update(client_team_id=team.id)
        if 'project_ids' in metadata:
            cleaned = dict(metadata)
            cleaned.pop('project_ids', None)
            team.metadata = cleaned or None
            team.save(update_fields=['metadata'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_add_file_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_team',
            field=models.ForeignKey(blank=True, db_column='client_team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='app.clientteam'),
        ),
        migrations.RunPython(migrate_project_links, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client_team'], name='projects_client__e6ee0e_idx'),
        ),
    ]
