# Generated by Django 4.2.27 on 2026-09-10

from django.db import migrations, models
import django.db.models.deletion


def backfill_asset_relationships(apps, schema_editor):
    ProjectFolder = apps.get_model('app', 'ProjectFolder')
    ProjectFile = apps.get_model('app', 'ProjectFile')
    for folder in ProjectFolder.objects.select_related('project').all().iterator():
        folder.workspace_id = folder.project.workspace_id
        folder.client_team_id = folder.project.client_team_id
        folder.save(update_fields=['workspace', 'client_team'])
    for item in ProjectFile.objects.select_related('project').all().iterator():
        item.workspace_id = item.project.workspace_id
        item.client_team_id = item.project.client_team_id
        item.save(update_fields=['workspace', 'client_team'])


class Migration(migrations.Migration):

    dependencies = [('app', '0021_project_client_team')]

    operations = [
        migrations.AddField(
            model_name='projectfolder', name='workspace',
            field=models.ForeignKey(db_column='workspace_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='projectfolder', name='client_team',
            field=models.ForeignKey(blank=True, db_column='client_team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.clientteam'),
        ),
        migrations.AddField(
            model_name='projectfile', name='workspace',
            field=models.ForeignKey(db_column='workspace_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='projectfile', name='client_team',
            field=models.ForeignKey(blank=True, db_column='client_team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.clientteam'),
        ),
        migrations.RunPython(backfill_asset_relationships, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projectfolder', name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.AlterField(
            model_name='projectfolder', name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project'),
        ),
        migrations.AlterField(
            model_name='projectfile', name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspace'),
        ),
        migrations.AlterField(
            model_name='projectfile', name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project'),
        ),
        migrations.RemoveConstraint(model_name='projectfile', name='project_files_project_file_uniq'),
        migrations.AddConstraint(
            model_name='projectfile',
            constraint=models.UniqueConstraint(fields=('workspace', 'file'), name='project_files_workspace_file_uniq'),
        ),
        migrations.AddIndex(model_name='projectfolder', index=models.Index(fields=['workspace'], name='project_fol_workspa_762095_idx')),
        migrations.AddIndex(model_name='projectfolder', index=models.Index(fields=['client_team'], name='project_fol_client__04f66f_idx')),
        migrations.AddIndex(model_name='projectfile', index=models.Index(fields=['workspace'], name='project_fil_workspa_bca348_idx')),
        migrations.AddIndex(model_name='projectfile', index=models.Index(fields=['client_team'], name='project_fil_client__9535b1_idx')),
    ]
