# Generated by Django 4.2.27 on 2026-09-10 21:20

from django.db import migrations, models
import django.db.models.deletion


def migrate_task_workflow(apps, schema_editor):
    Task = apps.get_model('app', 'Task')
    for task in Task.objects.select_related('project').filter(project__isnull=False).iterator():
        task.client_team_id = task.project.client_team_id
        task.save(update_fields=['client_team'])
    Task.objects.filter(status='IN_PROGRESS').update(status='REVISIONS')
    Task.objects.filter(status='COMPLETED').update(status='APPROVED')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('app', '0022_workspace_asset_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_team',
            field=models.ForeignKey(blank=True, db_column='client_team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.clientteam'),
        ),
        migrations.RunPython(migrate_task_workflow, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('REVISIONS', 'Revisions'), ('INTERNAL_QA', 'Internal Qa'), ('CLIENT', 'Client'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['client_team'], name='tasks_client__768a85_idx'),
        ),
    ]
