# Generated by Django 4.2.27 on 2026-09-10 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_task_stages(apps, schema_editor):
    Workspace = apps.get_model('app', 'Workspace')
    TaskStage = apps.get_model('app', 'TaskStage')
    Task = apps.get_model('app', 'Task')
    defaults = (
        ('TODO', 'To Do', '#89909d', False), ('REVISIONS', 'Revisions', '#ff5865', False),
        ('INTERNAL_QA', 'Internal QA', '#4ba3ff', False), ('CLIENT', 'Client', '#f4a742', False),
        ('APPROVED', 'Approved', '#36d399', True),
    )
    for workspace in Workspace.objects.all().iterator():
        stages = {}
        for order, (legacy, name, color, done) in enumerate(defaults):
            stage = TaskStage.objects.create(workspace=workspace, name=name, color=color, sort_order=order, is_done=done)
            stages[legacy] = stage
        for task in Task.objects.filter(workspace=workspace).iterator():
            task.task_stage_id = stages.get(task.status, stages['TODO']).id
            task.save(update_fields=['task_stage'])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('app', '0023_task_production_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#89909d', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('wip_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('automation_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_stages',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='task_workflow_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_stages', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_stage',
            field=models.ForeignKey(blank=True, db_column='task_stage_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='app.taskstage'),
        ),
        migrations.RunPython(seed_task_stages, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_stage'], name='tasks_task_st_0ca2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstage',
            index=models.Index(fields=['workspace', 'sort_order'], name='task_stages_workspa_aa059b_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskstage',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='task_stages_workspace_name_uniq'),
        ),
    ]
