# Generated by Django 4.2.27 on 2026-09-12 23:06

from django.db import migrations, models
import re

import django.db.models.deletion
import uuid


def group_existing_files_into_assets(apps, schema_editor):
    """Gives every existing file an asset, preserving the grouping already on screen.

    Before this, versions were inferred in the frontend from filenames — `hero_v1.mp4` and
    `hero_v2.mp4` read as one asset with two cuts. Backfilling with the same rule means the
    migration does not silently re-shuffle what people are already looking at; it just makes
    the grouping explicit and editable.
    """
    MediaAsset = apps.get_model('app', 'MediaAsset')
    ProjectFile = apps.get_model('app', 'ProjectFile')

    def version_key(title):
        without_extension = re.sub(r'\.[a-z0-9]{1,5}$', '', title.lower())
        without_marker = re.sub(r'[\s._-]*(?:v|ver|version)[\s._-]*\d+$', '', without_extension)
        return re.sub(r'[^a-z0-9]+', ' ', without_marker).strip()

    def version_number(title, fallback):
        match = re.search(r'(?:v|ver|version)[\s._-]*(\d+)$', re.sub(r'\.[a-z0-9]{1,5}$', '', title, flags=re.I), re.I)
        return int(match.group(1)) if match else fallback

    groups = {}
    rows = ProjectFile.objects.filter(media_asset__isnull=True).select_related('file').order_by('created_at')
    for row in rows:
        name = row.file.original_name
        groups.setdefault((row.workspace_id, row.project_id, row.folder_id, version_key(name)), []).append(row)

    for (workspace_id, _project_id, _folder_id, key), members in groups.items():
        ordered = sorted(
            members,
            key=lambda item: (version_number(item.file.original_name, 0), item.created_at),
        )
        asset = MediaAsset.objects.create(
            workspace_id=workspace_id,
            name=key.title() or ordered[0].file.original_name,
        )
        # Renumbered densely from 1: the numbers in the filenames may be sparse or absent.
        for position, row in enumerate(ordered, start=1):
            row.media_asset = asset
            row.version_number = position
            row.save(update_fields=['media_asset', 'version_number'])


def ungroup(apps, schema_editor):
    ProjectFile = apps.get_model('app', 'ProjectFile')
    ProjectFile.objects.update(media_asset=None, version_number=1)
    apps.get_model('app', 'MediaAsset').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_project_file_task_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_assets',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='projectfile',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='media_asset',
            field=models.ForeignKey(blank=True, db_column='media_asset_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app.mediaasset'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['media_asset'], name='project_fil_media_a_bc80bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectfile',
            constraint=models.UniqueConstraint(fields=('media_asset', 'version_number'), name='project_files_asset_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['workspace', 'updated_at'], name='media_asset_workspa_1c52fa_idx'),
        ),
        migrations.RunPython(group_existing_files_into_assets, ungroup),
    ]
