# Generated by Django 4.2.27 on 2026-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_task_stage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='visibility',
            field=models.CharField(choices=[('team', 'Team'), ('client', 'Client')], default='client', max_length=10),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['media_version', 'visibility'], name='review_comments_visibility_idx'),
        ),
    ]
