# Generated by Django 4.2.27 on 2026-10-03 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_review_comment_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested')], max_length=100),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested')], max_length=100)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationsetting',
            constraint=models.UniqueConstraint(fields=('user', 'workspace', 'kind'), name='notification_settings_user_workspace_kind_uniq'),
        ),
    ]
