# Generated by Django 4.2.27 on 2026-10-03 20:48

from django.db import migrations, models
import uuid

import django.db.models.deletion


def backfill_scope(apps, schema_editor):
    """Fill project/team_only on events written before the columns existed.

    A frozen copy of ``app.services.audit.resolve_audit_scope``: migrations must not import
    code that can change after them.
    """
    get = lambda name: apps.get_model('app', name)  # noqa: E731
    AuditLog = get('AuditLog')

    def key(value):
        try:
            return uuid.UUID(str(value))
        except (TypeError, ValueError):
            return None

    def comment_scope(comment_id):
        row = get('ReviewComment').objects.filter(id=comment_id).values(
            'media_version__project_id', 'visibility', 'parent_comment__visibility',
        ).first()
        if row is None:
            return None, False
        return row['media_version__project_id'], 'team' in (row['visibility'], row['parent_comment__visibility'])

    def scope(entity_type, entity_id):
        pk = key(entity_id)
        if pk is None:
            return None, False
        if entity_type == 'review_comment':
            return comment_scope(pk)
        if entity_type in ('review_comment_content', 'review_comment_reaction'):
            model = 'ReviewCommentContent' if entity_type == 'review_comment_content' else 'ReviewCommentReaction'
            comment_id = get(model).objects.filter(id=pk).values_list('review_comment_id', flat=True).first()
            return comment_scope(comment_id) if comment_id else (None, False)
        if entity_type == 'annotation':
            row = get('Annotation').objects.filter(id=pk).values('media_version__project_id', 'review_comment_id').first()
            if row is None:
                return None, False
            team = comment_scope(row['review_comment_id'])[1] if row['review_comment_id'] else False
            return row['media_version__project_id'], team
        simple = {
            'media_version': ('MediaVersion', 'project_id'),
            'task': ('Task', 'project_id'),
            'guest_invite': ('GuestInvite', 'project_id'),
            'guest_review_access': ('GuestReviewAccess', 'guest_invite__project_id'),
        }
        if entity_type in simple:
            model, field = simple[entity_type]
            return get(model).objects.filter(id=pk).values_list(field, flat=True).first(), False
        return None, False

    for row in AuditLog.objects.filter(project__isnull=True).only('id', 'entity_type', 'entity_id').iterator():
        project_id, team_only = scope(row.entity_type, row.entity_id)
        if project_id or team_only:
            AuditLog.objects.filter(id=row.id).update(project_id=project_id, team_only=team_only)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_project_deliverable_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='team_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['project', 'created_at'], name='audit_logs_project_fafa32_idx'),
        ),
        migrations.RunPython(backfill_scope, migrations.RunPython.noop),
    ]
