# Generated by Django 4.2.27 on 2026-10-03 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


BILLING_KEYS = ('billing.view', 'billing.manage', 'billing.rates.view')


def grant_billing_to_admin_roles(apps, schema_editor):
    """Owners and admins get the billing keys: every role that can already manage the workspace."""
    RolePermission = apps.get_model('app', 'RolePermission')
    role_ids = set(RolePermission.objects.filter(permission_key='workspace.manage').values_list('role_id', flat=True))
    existing = set(RolePermission.objects.filter(role_id__in=role_ids, permission_key__in=BILLING_KEYS).values_list('role_id', 'permission_key'))
    RolePermission.objects.bulk_create([
        RolePermission(role_id=role_id, permission_key=key)
        for role_id in role_ids for key in BILLING_KEYS if (role_id, key) not in existing
    ])


def revoke_billing_keys(apps, schema_editor):
    apps.get_model('app', 'RolePermission').objects.filter(permission_key__in=BILLING_KEYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_audit_log_project_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_team', models.ForeignKey(db_column='client_team_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.clientteam')),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='MemberPayRate',
            fields=[
                ('workspace_membership', models.OneToOneField(db_column='workspace_membership_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='app.workspacemembership')),
                ('default_task_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member_pay_rates',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceBillingSettings',
            fields=[
                ('workspace', models.OneToOneField(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='app.workspace')),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('payment_terms_days', models.PositiveIntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspace_billing_settings',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='client_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_fee_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='client_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='client_price_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('project_fee', 'Project Fee'), ('task', 'Task')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.invoice')),
                ('task', models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.task')),
            ],
            options={
                'db_table': 'invoice_lines',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='workspace',
            field=models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace'),
        ),
        migrations.CreateModel(
            name='EditorPay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned')], default='pending', max_length=10)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.task')),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
                ('workspace_membership', models.ForeignKey(db_column='workspace_membership_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.workspacemembership')),
            ],
            options={
                'db_table': 'editor_pay',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('paid_on', models.DateField()),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('provider', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app.invoice')),
                ('payee_membership', models.ForeignKey(blank=True, db_column='payee_membership_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.workspacemembership')),
                ('recorded_by_user', models.ForeignKey(blank=True, db_column='recorded_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['workspace', 'direction'], name='payments_workspa_7fe198_idx'), models.Index(fields=['payee_membership'], name='payments_payee_m_d82f66_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payments_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('direction', 'incoming'), ('invoice__isnull', False), ('payee_membership__isnull', True)), models.Q(('direction', 'outgoing'), ('invoice__isnull', True), ('payee_membership__isnull', False)), _connector='OR'), name='payments_direction_matches_target'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__isnull', False)), fields=('provider', 'provider_reference'), name='payments_provider_reference_uniq'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['workspace', 'status'], name='invoices_workspa_f9f536_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client_team'], name='invoices_client__7fc479_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('workspace', 'number'), name='invoices_workspace_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='editorpay',
            index=models.Index(fields=['workspace', 'workspace_membership', 'status'], name='editor_pay_workspa_19dc22_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorpay',
            constraint=models.UniqueConstraint(fields=('task', 'workspace_membership'), name='editor_pay_task_membership_uniq'),
        ),
        migrations.AddConstraint(
            model_name='editorpay',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='editor_pay_amount_non_negative'),
        ),
        migrations.RunPython(grant_billing_to_admin_roles, revoke_billing_keys),
    ]
