# Generated by Django 4.2.27 on 2026-10-03 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_audit_log_project_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaversionstageentry',
            name='changed_by_guest_session',
            field=models.ForeignKey(blank=True, db_column='changed_by_guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession'),
        ),
        migrations.AlterField(
            model_name='mediaversionstageentry',
            name='changed_by_user',
            field=models.ForeignKey(blank=True, db_column='changed_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes requested')], max_length=30)),
                ('reviewer_name', models.CharField(max_length=150)),
                ('reviewer_email', models.CharField(max_length=255)),
                ('open_notes_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('decided_by_user', models.ForeignKey(blank=True, db_column='decided_by_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('guest_invite', models.ForeignKey(blank=True, db_column='guest_invite_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestinvite')),
                ('guest_review_access', models.ForeignKey(blank=True, db_column='guest_review_access_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestreviewaccess')),
                ('guest_session', models.ForeignKey(blank=True, db_column='guest_session_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.guestsession')),
                ('media_version', models.ForeignKey(db_column='media_version_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.mediaversion')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.project')),
                ('review_comment', models.ForeignKey(blank=True, db_column='review_comment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.reviewcomment')),
                ('stage_entry', models.ForeignKey(blank=True, db_column='stage_entry_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.mediaversionstageentry')),
            ],
            options={
                'db_table': 'review_decisions',
                'indexes': [models.Index(fields=['media_version', 'created_at'], name='review_decisions_media_idx'), models.Index(fields=['project', 'created_at'], name='review_decisions_project_idx'), models.Index(fields=['guest_invite'], name='review_decisions_invite_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reviewdecision',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decided_by_user__isnull', True), ('guest_session__isnull', False)), models.Q(('decided_by_user__isnull', False), ('guest_session__isnull', True)), _connector='OR'), name='review_decisions_exactly_one_reviewer'),
        ),
    ]
