# Generated by Django 4.2.27 on 2026-10-04 21:43

from django.db import migrations, models
from django.db.models import F, Q

"""
Annotations already carry ``start_time_ms``/``end_time_ms``; the review player now uses
that pair as the window a drawing stays on screen (and a comment's pair as its in/out
range). This guards both windows at the database level. Any existing row that would break
the rule (an end before its start, or an end with no start) has its end cleared first, so
it falls back to the default display duration instead of blocking the migration.
"""


def clear_broken_windows(apps, schema_editor):
    broken = Q(end_time_ms__isnull=False) & (Q(start_time_ms__isnull=True) | Q(end_time_ms__lt=F('start_time_ms')))
    for name in ('Annotation', 'ReviewComment'):
        apps.get_model('app', name).objects.filter(broken).update(end_time_ms=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_billing_demo'),
    ]

    operations = [
        migrations.RunPython(clear_broken_windows, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(check=models.Q(('end_time_ms__isnull', True), models.Q(('end_time_ms__gte', models.F('start_time_ms')), ('start_time_ms__isnull', False)), _connector='OR'), name='annotations_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='reviewcomment',
            constraint=models.CheckConstraint(check=models.Q(('end_time_ms__isnull', True), models.Q(('end_time_ms__gte', models.F('start_time_ms')), ('start_time_ms__isnull', False)), _connector='OR'), name='review_comments_end_after_start'),
        ),
    ]
