# Generated by Django 4.2.27 on 2026-10-04 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_annotation_display_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested'), ('CLIENT_UPLOAD_RECEIVED', 'Client Upload Received')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='kind',
            field=models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested'), ('CLIENT_UPLOAD_RECEIVED', 'Client Upload Received')], max_length=100),
        ),
        migrations.CreateModel(
            name='UploadLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True, default='')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_file_bytes', models.BigIntegerField(blank=True, null=True)),
                ('allowed_kinds', models.JSONField(blank=True, default=list)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by_workspace_membership', models.ForeignKey(db_column='created_by_workspace_membership_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.workspacemembership')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='upload_links', to='app.project')),
                ('revoked_by_user', models.ForeignKey(blank=True, db_column='revoked_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'upload_links',
            },
        ),
        migrations.CreateModel(
            name='ClientUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uploader_name', models.CharField(max_length=120)),
                ('uploader_email', models.EmailField(max_length=255)),
                ('batch_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_uploads', to='app.project')),
                ('project_file', models.OneToOneField(db_column='project_file_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_upload', to='app.projectfile')),
                ('upload_link', models.ForeignKey(blank=True, db_column='upload_link_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='app.uploadlink')),
                ('uploaded_by_user', models.ForeignKey(blank=True, db_column='uploaded_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'client_uploads',
            },
        ),
        migrations.AddIndex(
            model_name='uploadlink',
            index=models.Index(fields=['project', 'created_at'], name='upload_link_project_0dd1ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadlink',
            constraint=models.CheckConstraint(check=models.Q(('max_file_bytes__isnull', True), ('max_file_bytes__gt', 0), _connector='OR'), name='upload_links_max_file_bytes_positive'),
        ),
        migrations.AddIndex(
            model_name='clientupload',
            index=models.Index(fields=['project', 'created_at'], name='client_uplo_project_27cc55_idx'),
        ),
        migrations.AddIndex(
            model_name='clientupload',
            index=models.Index(fields=['upload_link', 'created_at'], name='client_uplo_upload__e54634_idx'),
        ),
        migrations.AddIndex(
            model_name='clientupload',
            index=models.Index(fields=['batch_id'], name='client_uplo_batch_i_a071e0_idx'),
        ),
    ]
