# Generated by Django 4.2.27 on 2026-10-04 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_client_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceprofile',
            name='brand_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='workspaceprofile',
            name='logo_mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workspaceprofile',
            name='logo_object_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workspaceprofile',
            name='logo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceprofile',
            name='portal_welcome',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested'), ('CLIENT_UPLOAD_RECEIVED', 'Client Upload Received'), ('PROJECT_REQUEST_NEW', 'Project Request New'), ('PROJECT_REQUEST_DECIDED', 'Project Request Decided')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='kind',
            field=models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested'), ('CLIENT_UPLOAD_RECEIVED', 'Client Upload Received'), ('PROJECT_REQUEST_NEW', 'Project Request New'), ('PROJECT_REQUEST_DECIDED', 'Project Request Decided')], max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('requester_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('platform', models.CharField(blank=True, max_length=40, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=10, null=True)),
                ('target_length_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('brief', models.TextField()),
                ('references', models.TextField(blank=True, default='')),
                ('wanted_by', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the studio'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_team', models.ForeignKey(db_column='client_team_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_requests', to='app.clientteam')),
                ('decided_by_user', models.ForeignKey(blank=True, db_column='decided_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.project')),
                ('requested_by_user', models.ForeignKey(blank=True, db_column='requested_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'project_requests',
                'indexes': [models.Index(fields=['workspace', 'status', 'created_at'], name='project_req_workspa_6078af_idx'), models.Index(fields=['client_team', 'created_at'], name='project_req_client__30212f_idx')],
            },
        ),
    ]
