# Generated by Django 4.2.27 on 2026-10-04 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_client_portal_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('client', 'With client'), ('team', 'Team only')], max_length=10)),
                ('author_name', models.CharField(max_length=150)),
                ('author_is_client', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, default='')),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_user', models.ForeignKey(blank=True, db_column='author_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.project')),
                ('reply_to', models.ForeignKey(blank=True, db_column='reply_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.projectmessage')),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'project_messages',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested'), ('CLIENT_UPLOAD_RECEIVED', 'Client Upload Received'), ('PROJECT_REQUEST_NEW', 'Project Request New'), ('PROJECT_REQUEST_DECIDED', 'Project Request Decided'), ('PROJECT_MESSAGE_NEW', 'Project Message New'), ('PROJECT_MESSAGE_MENTION', 'Project Message Mention')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='kind',
            field=models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested'), ('CLIENT_UPLOAD_RECEIVED', 'Client Upload Received'), ('PROJECT_REQUEST_NEW', 'Project Request New'), ('PROJECT_REQUEST_DECIDED', 'Project Request Decided'), ('PROJECT_MESSAGE_NEW', 'Project Message New'), ('PROJECT_MESSAGE_MENTION', 'Project Message Mention')], max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectMessageRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('client', 'With client'), ('team', 'Team only')], max_length=10)),
                ('last_read_at', models.DateTimeField()),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_message_reads',
            },
        ),
        migrations.CreateModel(
            name='ProjectMessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('upload', 'Upload'), ('file', 'Project file'), ('cut', 'Cut')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.file')),
                ('media_version', models.ForeignKey(blank=True, db_column='media_version_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.mediaversion')),
                ('message', models.ForeignKey(blank=True, db_column='message_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.projectmessage')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.project')),
                ('project_file', models.ForeignKey(blank=True, db_column='project_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.projectfile')),
                ('uploaded_by_user', models.ForeignKey(blank=True, db_column='uploaded_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'project_message_attachments',
            },
        ),
        migrations.AddConstraint(
            model_name='projectmessageread',
            constraint=models.UniqueConstraint(fields=('user', 'project', 'channel'), name='project_message_reads_uniq'),
        ),
        migrations.AddIndex(
            model_name='projectmessageattachment',
            index=models.Index(fields=['message'], name='project_mes_message_bc1a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmessageattachment',
            index=models.Index(fields=['project', 'created_at'], name='project_mes_project_932158_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmessage',
            index=models.Index(fields=['project', 'channel', 'created_at'], name='project_mes_project_ac3fb3_idx'),
        ),
    ]
