# Generated by Django 4.2.27 on 2026-10-10 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_chat_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='source',
            field=models.CharField(default='human', max_length=20),
        ),
        migrations.CreateModel(
            name='AIReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_checksum', models.CharField(blank=True, max_length=512, null=True)),
                ('review_type', models.CharField(default='VISUAL_TEXT_QA', max_length=40)),
                ('mode', models.CharField(choices=[('PROOFREAD', 'Proofread')], default='PROOFREAD', max_length=40)),
                ('language', models.CharField(default='en-GB', max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('stage', models.CharField(default='queued', max_length=40)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('engine', models.CharField(blank=True, default='', max_length=60)),
                ('engine_version', models.CharField(blank=True, default='', max_length=60)),
                ('pipeline_version', models.CharField(max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('options_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.mediaversion')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'ai_reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIFrameObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_ms', models.BigIntegerField(blank=True, null=True)),
                ('frame_index', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('confidence', models.FloatField()),
                ('polygon', models.JSONField(default=list)),
                ('engine', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='app.aireview')),
            ],
            options={
                'db_table': 'ai_frame_observations',
            },
        ),
        migrations.CreateModel(
            name='AIFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('POSSIBLE_SPELLING_ERROR', 'Possible Spelling Error'), ('OCR_UNCERTAIN', 'Ocr Uncertain')], max_length=40)),
                ('band', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('detected_text', models.CharField(max_length=500)),
                ('suggested_text', models.CharField(blank=True, default='', max_length=500)),
                ('edited_suggestion', models.CharField(blank=True, default='', max_length=500)),
                ('context_text', models.CharField(blank=True, default='', max_length=1000)),
                ('explanation', models.CharField(blank=True, default='', max_length=500)),
                ('ocr_confidence', models.FloatField()),
                ('decision_confidence', models.FloatField()),
                ('region', models.JSONField(default=dict)),
                ('start_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('end_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('observation_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DISMISSED', 'Dismissed'), ('NOT_AN_ERROR', 'Not An Error'), ('COMMENT_CREATED', 'Comment Created')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='app.aireview')),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_finding', to='app.reviewcomment')),
                ('media_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.mediaversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'ai_findings',
                'ordering': ('region__y', 'region__x', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=200)),
                ('normalized', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('brand', 'Brand'), ('product', 'Product'), ('name', 'Name'), ('acronym', 'Acronym'), ('stylisation', 'Stylisation'), ('other', 'Other')], default='other', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.workspace')),
            ],
            options={
                'db_table': 'glossary_terms',
                'ordering': ('normalized',),
                'indexes': [models.Index(fields=['workspace', 'project'], name='glossary_te_workspa_dfa4f2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='glossaryterm',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('workspace', 'normalized'), name='glossary_terms_workspace_term_uniq'),
        ),
        migrations.AddConstraint(
            model_name='glossaryterm',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('workspace', 'project', 'normalized'), name='glossary_terms_project_term_uniq'),
        ),
        migrations.AddIndex(
            model_name='aireview',
            index=models.Index(fields=['media_version', 'created_at'], name='ai_reviews_media_v_96f947_idx'),
        ),
        migrations.AddIndex(
            model_name='aireview',
            index=models.Index(fields=['workspace', 'status'], name='ai_reviews_workspa_bbb70f_idx'),
        ),
        migrations.AddIndex(
            model_name='aireview',
            index=models.Index(fields=['workspace', 'created_at'], name='ai_reviews_workspa_a1d2c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='aireview',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'PROCESSING'])), fields=('media_version', 'options_hash', 'pipeline_version'), name='ai_reviews_one_active_run_per_options'),
        ),
        migrations.AddIndex(
            model_name='aiframeobservation',
            index=models.Index(fields=['ai_review', 'frame_index'], name='ai_frame_ob_ai_revi_8bd59b_idx'),
        ),
        migrations.AddIndex(
            model_name='aifinding',
            index=models.Index(fields=['media_version', 'dedupe_key'], name='ai_findings_media_v_250714_idx'),
        ),
        migrations.AddIndex(
            model_name='aifinding',
            index=models.Index(fields=['ai_review', 'status'], name='ai_findings_ai_revi_0fda2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='aifinding',
            constraint=models.UniqueConstraint(fields=('ai_review', 'dedupe_key'), name='ai_findings_review_dedupe_uniq'),
        ),
    ]
