# Generated by Django 4.2.27 on 2026-10-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_ai_visual_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifinding',
            name='track',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested'), ('CLIENT_UPLOAD_RECEIVED', 'Client Upload Received'), ('PROJECT_REQUEST_NEW', 'Project Request New'), ('PROJECT_REQUEST_DECIDED', 'Project Request Decided'), ('AI_QA_COMPLETED', 'Ai Qa Completed'), ('PROJECT_MESSAGE_NEW', 'Project Message New'), ('PROJECT_MESSAGE_MENTION', 'Project Message Mention')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='kind',
            field=models.CharField(choices=[('REVIEW_COMMENT_MENTION', 'Review Comment Mention'), ('TASK_CLIENT_READY', 'Task Client Ready'), ('REVIEW_COMMENT_NEW', 'Review Comment New'), ('REVIEW_COMMENT_REPLY', 'Review Comment Reply'), ('MEDIA_VERSION_NEW', 'Media Version New'), ('TASK_ASSIGNED', 'Task Assigned'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_CHANGES_REQUESTED', 'Media Changes Requested'), ('CLIENT_UPLOAD_RECEIVED', 'Client Upload Received'), ('PROJECT_REQUEST_NEW', 'Project Request New'), ('PROJECT_REQUEST_DECIDED', 'Project Request Decided'), ('AI_QA_COMPLETED', 'Ai Qa Completed'), ('PROJECT_MESSAGE_NEW', 'Project Message New'), ('PROJECT_MESSAGE_MENTION', 'Project Message Mention')], max_length=100),
        ),
    ]
