from django.urls import path

from .views import (
    current_user,
    annotation_detail,
    annotation_list_create,
    annotation_revisions,
    delivery_health,
    email_verification_confirm,
    email_verification_request,
    health_check,
    login_user,
    password_change,
    password_reset_confirm,
    password_reset_request,
    logout_user,
    media_version_detail,
    media_version_download,
    media_version_list_create,
    media_version_workflow,
    media_revision_request,
    notification_list,
    notification_preferences,
    notification_read,
    notification_read_all,
    operations_health,
    operations_metrics,
    review_comment_detail,
    review_comment_list_create,
    review_comment_resolution,
    review_comment_reactions,
    review_comment_revisions,
    review_attachment_detail,
    review_attachment_preview,
    review_attachment_upload,
    accept_workspace_invitation,
    project_detail,
    project_access_detail,
    project_access_list_create,
    project_list_create,
    register,
    workspace_invitations,
    workspace_list_create,
    workspace_member_detail,
    workspace_members,
    workspace_roles,
    workspace_role_detail,
    workspace_retention_policy,
    workspace_workflow_stages,
)
from .guest_views import (
    guest_annotation_detail, guest_annotation_revisions, guest_annotations,
    guest_attachment_download, guest_attachment_preview,
    guest_access_key_rotate, guest_attachment_upload, guest_comments, guest_exchange, guest_review,
    guest_comment_detail, guest_comment_revisions,
    guest_comment_reactions,
    project_guest_access_detail, project_guest_invite_detail, project_guest_invites,
)

urlpatterns = [
    path('health/', health_check, name='api-health'),
    path('auth/register/', register, name='api-register'),
    path('auth/login/', login_user, name='api-login'),
    path('auth/password-reset/request/', password_reset_request, name='api-password-reset-request'),
    path('auth/password-reset/confirm/', password_reset_confirm, name='api-password-reset-confirm'),
    path('auth/email-verification/request/', email_verification_request, name='api-email-verification-request'),
    path('auth/email-verification/confirm/', email_verification_confirm, name='api-email-verification-confirm'),
    path('auth/password/change/', password_change, name='api-password-change'),
    path('auth/logout/', logout_user, name='api-logout'),
    path('auth/me/', current_user, name='api-current-user'),
    path('notifications/', notification_list, name='api-notifications'),
    path('notification-preferences/', notification_preferences, name='api-notification-preferences'),
    path('notifications/read-all/', notification_read_all, name='api-notifications-read-all'),
    path('notifications/<uuid:notification_id>/read/', notification_read, name='api-notification-read'),
    path('guest-access/exchange/', guest_exchange, name='api-guest-exchange'),
    path('guest/reviews/<uuid:project_id>/', guest_review, name='api-guest-review'),
    path('guest/reviews/<uuid:project_id>/access-key/rotate/', guest_access_key_rotate, name='api-guest-access-key-rotate'),
    path('guest/reviews/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/', guest_comments, name='api-guest-comments'),
    path('guest/reviews/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/', guest_comment_detail, name='api-guest-comment-detail'),
    path('guest/reviews/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/revisions/', guest_comment_revisions, name='api-guest-comment-revisions'),
    path('guest/reviews/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/reactions/', guest_comment_reactions, name='api-guest-comment-reactions'),
    path('guest/reviews/<uuid:project_id>/media-versions/<uuid:media_version_id>/annotations/', guest_annotations, name='api-guest-annotations'),
    path('guest/reviews/<uuid:project_id>/media-versions/<uuid:media_version_id>/annotations/<uuid:annotation_id>/', guest_annotation_detail, name='api-guest-annotation-detail'),
    path('guest/reviews/<uuid:project_id>/media-versions/<uuid:media_version_id>/annotations/<uuid:annotation_id>/revisions/', guest_annotation_revisions, name='api-guest-annotation-revisions'),
    path('guest/reviews/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/attachments/', guest_attachment_upload, name='api-guest-attachment-upload'),
    path('guest/reviews/<uuid:project_id>/attachments/<uuid:content_id>/', guest_attachment_download, name='api-guest-attachment'),
    path('guest/reviews/<uuid:project_id>/attachments/<uuid:content_id>/previews/<uuid:variant_id>/', guest_attachment_preview, name='api-guest-attachment-preview'),
    path('workspaces/', workspace_list_create, name='api-workspaces'),
    path('workspace-invitations/accept/', accept_workspace_invitation, name='api-workspace-invite-accept'),
    path('workspaces/<uuid:workspace_id>/roles/', workspace_roles, name='api-workspace-roles'),
    path('workspaces/<uuid:workspace_id>/workflow-stages/', workspace_workflow_stages, name='api-workflow-stages'),
    path('workspaces/<uuid:workspace_id>/delivery-health/', delivery_health, name='api-delivery-health'),
    path('workspaces/<uuid:workspace_id>/operations/health/', operations_health, name='api-operations-health'),
    path('workspaces/<uuid:workspace_id>/operations/metrics/', operations_metrics, name='api-operations-metrics'),
    path('workspaces/<uuid:workspace_id>/retention-policy/', workspace_retention_policy, name='api-workspace-retention-policy'),
    path('workspaces/<uuid:workspace_id>/roles/<uuid:role_id>/', workspace_role_detail, name='api-workspace-role-detail'),
    path('workspaces/<uuid:workspace_id>/members/', workspace_members, name='api-workspace-members'),
    path('workspaces/<uuid:workspace_id>/members/<uuid:membership_id>/', workspace_member_detail, name='api-workspace-member-detail'),
    path('workspaces/<uuid:workspace_id>/invitations/', workspace_invitations, name='api-workspace-invitations'),
    path('workspaces/<uuid:workspace_id>/projects/', project_list_create, name='api-projects'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/', project_detail, name='api-project-detail'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/guest-invites/', project_guest_invites, name='api-project-guest-invites'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/guest-invites/<uuid:invite_id>/', project_guest_invite_detail, name='api-project-guest-invite-detail'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/guest-access/<uuid:access_id>/', project_guest_access_detail, name='api-project-guest-access-detail'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/access/', project_access_list_create, name='api-project-access'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/access/<uuid:grant_id>/', project_access_detail, name='api-project-access-detail'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/', media_version_list_create, name='api-media-versions'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/', media_version_detail, name='api-media-version-detail'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/download/', media_version_download, name='api-media-version-download'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/workflow/', media_version_workflow, name='api-media-version-workflow'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/', review_comment_list_create, name='api-review-comments'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/', review_comment_detail, name='api-review-comment-detail'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/resolution/', review_comment_resolution, name='api-review-comment-resolution'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/revisions/', review_comment_revisions, name='api-review-comment-revisions'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/reactions/', review_comment_reactions, name='api-review-comment-reactions'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/attachments/', review_attachment_upload, name='api-review-attachment-upload'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/attachments/<uuid:content_id>/', review_attachment_detail, name='api-review-attachment-detail'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/comments/<uuid:comment_id>/attachments/<uuid:content_id>/previews/<uuid:variant_id>/', review_attachment_preview, name='api-review-attachment-preview'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/annotations/', annotation_list_create, name='api-annotations'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/annotations/<uuid:annotation_id>/', annotation_detail, name='api-annotation-detail'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/annotations/<uuid:annotation_id>/revisions/', annotation_revisions, name='api-annotation-revisions'),
    path('workspaces/<uuid:workspace_id>/projects/<uuid:project_id>/media-versions/<uuid:media_version_id>/revision-requests/', media_revision_request, name='api-media-revision-request'),
]
